// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChNBBTcsPjZR4BjTSp8OydQ6t6lOuhNus',
    appId: '1:779502022865:web:e951c75b8b321038c115f0',
    messagingSenderId: '779502022865',
    projectId: 'barber-app-cc311',
    authDomain: 'barber-app-cc311.firebaseapp.com',
    storageBucket: 'barber-app-cc311.appspot.com',
    measurementId: 'G-BYY138N5FV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUZiNiiYBdHVw_N6HgRlkqYfQJITPhXjs',
    appId: '1:779502022865:android:f1e42ffb5ef87385c115f0',
    messagingSenderId: '779502022865',
    projectId: 'barber-app-cc311',
    storageBucket: 'barber-app-cc311.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz-t9Est_ruwD6Y6bxg5NV7Pc_18Rl-UQ',
    appId: '1:779502022865:ios:4c2cc791420ae295c115f0',
    messagingSenderId: '779502022865',
    projectId: 'barber-app-cc311',
    storageBucket: 'barber-app-cc311.appspot.com',
    iosBundleId: 'com.example.barberbooking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDz-t9Est_ruwD6Y6bxg5NV7Pc_18Rl-UQ',
    appId: '1:779502022865:ios:4c2cc791420ae295c115f0',
    messagingSenderId: '779502022865',
    projectId: 'barber-app-cc311',
    storageBucket: 'barber-app-cc311.appspot.com',
    iosBundleId: 'com.example.barberbooking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChNBBTcsPjZR4BjTSp8OydQ6t6lOuhNus',
    appId: '1:779502022865:web:9e304cd7f4c68fbdc115f0',
    messagingSenderId: '779502022865',
    projectId: 'barber-app-cc311',
    authDomain: 'barber-app-cc311.firebaseapp.com',
    storageBucket: 'barber-app-cc311.appspot.com',
    measurementId: 'G-YL039768P5',
  );
}
